import { DATA } from './data/alphabetData.js';
import { CHARS } from './data/chars.js';
import { MORPHEMES } from './data/morphemes.js';
import { QUICK_STEM_METHODS } from './data/quickStemMethods.js';
import { STEM_TOPICS } from './data/stemTopics.js';
import { STRATEGY_CARDS } from './data/strategyCards.js';
import { QB, STUDY_GUIDES, ACCU_SAMPLE_PDFS, ACCU_IXL_PLANS } from './data/qxData.js';

const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const esc = v => String(v ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const state = { mode:'explore', cur:0, start:Date.now(), running:false, elapsed:0, streak:+localStorage.ls_streak||0, revealed:{}, morph:{q:'',cat:'all',origin:'all',kind:'all'}, strategy:'All', stemCat:'All', quiz:{track:'quiz',cat:'mixed',ap:'calc-ab',clep:'college-algebra',accu:'arithmetic',score:0,total:0,chosen:null,current:null,seen:{},sheet:[],missed:{},strong:{},scaled:250,difficulty:1,essay:''} };
const letters = DATA.map(x=>({...x,h:x.heb,name:x.hname,hebrew:x.hname,symbol:x.sym,meanings:x.means||[],sound:(x.ipa_desc||[]).join(' · '),note:`${x.sym}: ${(x.means||[]).join(', ')}`,chars:CHARS[x.l]||[]}));
const cats=['all','common','research','legal','college','livelihood'], origins=['all','Latin','Greek','French','Germanic'], kinds=['all','prefix','root','suffix'];
const MODE_GROUPS=[{label:'Language',items:[['explore','Letter Roots'],['vocab','Word Bank'],['morph','Word Parts'],['counts','Morpheme Index']]},{label:'Practice',items:[['quiz','Practice Quiz'],['ap','AP Practice'],['clep','CLEP Practice'],['accuplacer','ACCUPLACER']]},{label:'Learn',items:[['stem','Formula Lab'],['strategy','Study Science']]}];
const icons={roots:'<svg viewBox="0 0 24 24"><path d="M4 6h16M7 6v12m10-12v12M5 18h14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',words:'<svg viewBox="0 0 24 24"><path d="M5 4h10a4 4 0 0 1 4 4v12H7a2 2 0 0 1-2-2V4Z" fill="none" stroke="currentColor" stroke-width="2"/><path d="M8 8h7M8 12h6" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',parts:'<svg viewBox="0 0 24 24"><path d="M8 4h5v5H8zM13 9h5v5h-5zM6 14h5v5H6z" fill="none" stroke="currentColor" stroke-width="2"/></svg>',quiz:'<svg viewBox="0 0 24 24"><path d="M5 19l4-1 9-9-3-3-9 9-1 4Z" fill="none" stroke="currentColor" stroke-width="2"/><path d="M13 6l3 3" stroke="currentColor" stroke-width="2"/></svg>',lab:'<svg viewBox="0 0 24 24"><path d="M10 3v6l-5 9a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-9V3" fill="none" stroke="currentColor" stroke-width="2"/><path d="M8 15h8" stroke="currentColor" stroke-width="2"/></svg>',more:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="2" fill="currentColor"/><circle cx="12" cy="12" r="2" fill="currentColor"/><circle cx="19" cy="12" r="2" fill="currentColor"/></svg>',reset:'<svg viewBox="0 0 24 24"><path d="M4 12a8 8 0 1 0 2.3-5.7L4 8.5M4 4v4.5h4.5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',link:'<svg viewBox="0 0 24 24"><path d="M7 17L17 7M9 7h8v8" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>'};
function tag(t){return `<span class="tag">${esc(t)}</span>`} function section(t){return `<div class="section">${esc(t)}</div>`}
function allMorph(){return Object.entries(MORPHEMES).flatMap(([letter,arr])=>arr.map((e,i)=>({...e,letter,index:i,id:`morph-${letter}-${i}`})))}
function entriesFor(l){return (MORPHEMES[l]||[]).map((e,i)=>({...e,letter:l,index:i,id:`morph-${l}-${i}`}))}
function typeCount(list,type){return list.filter(e=>e.type.toLowerCase().includes(type)).length}
function filterMorph(list){const m=state.morph,q=m.q.trim().toLowerCase();return list.filter(e=>(m.cat==='all'||(e.cats||[]).includes(m.cat))&&(m.origin==='all'||e.origin.toLowerCase().includes(m.origin.toLowerCase()))&&(m.kind==='all'||e.type.toLowerCase().includes(m.kind.toLowerCase()))&&(!q||[e.m,e.type,e.origin,e.meaning,e.examples,(e.cats||[]).join(' ')].join(' ').toLowerCase().includes(q)))}
function topbar(){return `<div class="topbar"><div class="header"><div class="brandrow"><div class="logo">LS</div><div><div class="brand">STEM Study Lab</div><div class="subtitle">Language roots · STEM formulas · exam prep</div></div></div><div class="actions"><span class="streak">streak: ${state.streak}</span><button class="btn icon" data-reset-streak>${icons.reset}</button><button class="timer" data-timer>${timerLabel()}</button></div></div><div class="navscroll">${MODE_GROUPS.map((g,i)=>`<div class="navgroup"><span class="grouplabel">${g.label}</span>${g.items.map(([m,l])=>`<button class="pill ${activeMode(m)?'active':''}" data-mode="${m}">${l}</button>`).join('')}${i<MODE_GROUPS.length-1?'<span class="divider"></span>':''}</div>`).join('')}</div></div><div class="progress"><span style="width:${letterMode()?Math.max(2,(state.cur+1)/letters.length*100):100}%"></span></div>`}
function activeMode(m){return state.mode===m||(m==='quiz'&&['quiz','ap','clep','accuplacer'].includes(state.mode))} function letterMode(){return ['explore','vocab','morph'].includes(state.mode)}
function timerLabel(){let ms=state.elapsed+(state.running?Date.now()-state.start:0),s=Math.floor(ms/1000),m=Math.floor(s/60);s%=60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function explore(){const item=letters[state.cur];return `<div class="content"><div class="card"><div class="hero"><div class="glyphbox"><div class="glyph">${esc(item.l)}</div><div class="hebrew">${esc(item.h)}</div></div><div><div class="name">${esc(item.name)}</div><div class="subname">${esc(item.hebrew)}</div><span class="symbol">${esc(item.symbol)}</span><div class="row">${item.meanings.map(tag).join('')}</div><div class="ipa"><span class="ipasym">${esc(item.ipa)}</span> · ${esc(item.sound)}</div><div class="muted">${esc(item.note)}</div></div></div></div><div class="split"><div class="soft">${section('Vocabulary seed')}${(item.vocab||[]).slice(0,8).map(v=>`<div class="text"><span class="smalltitle">${esc(v.w)}</span> ${esc(v.ipa)} — ${esc(v.def)}</div>`).join('')}</div><div class="soft">${section('Language links')}${(item.langs||[]).slice(0,8).map(l=>`<div class="text"><span class="smalltitle">${esc(l.lang)}</span>: ${esc(l.word)} ${l.ipa?`· ${esc(l.ipa)}`:''}</div>`).join('')}</div></div><div class="soft">${section('Root families')}${(item.roots||[]).map(r=>`<div class="text"><span class="smalltitle">${esc(r.fam)}</span> — ${esc(r.root)}: ${esc(r.meaning)}</div>`).join('')}</div><div class="soft">${section('Character cousins')}<div class="grid">${(item.chars||[]).map(c=>`<div class="charcard"><div class="charscript">${esc(c.script)}</div><div class="charglyph">${esc(c.chars)}</div><div class="charname">${esc(c.name)}</div><div class="muted">${esc(c.note)}</div></div>`).join('')}</div></div></div>`}
function vocab(){const item=letters[state.cur];return `<div class="content"><div class="card">${section(`${item.l} word bank`)}<div class="muted">Tap a card to reveal its meaning, root, and memory hook.</div></div><div class="grid">${(item.vocab||[]).map(v=>{let open=state.revealed[v.w];return `<button class="wordcard ${open?'open':''}" data-reveal="${esc(v.w)}"><div class="word">${esc(v.w)}</div><div class="meta mono">${esc(v.ipa)}</div>${open?`<div class="meaning">${esc(v.def)}</div><div class="muted">${esc(v.root)}</div>`:`<div class="hint">tap to reveal</div>`}</button>`}).join('')}</div></div>`}
function filters(){return `<div class="card"><input class="search" data-mq placeholder="Search morphemes..." value="${esc(state.morph.q)}">${section('Category')}<div class="row">${cats.map(x=>`<button class="chip ${state.morph.cat===x?'active':''}" data-mf="cat:${x}">${x}</button>`).join('')}</div>${section('Origin')}<div class="row">${origins.map(x=>`<button class="chip ${state.morph.origin===x?'active':''}" data-mf="origin:${x}">${x}</button>`).join('')}</div>${section('Type')}<div class="row">${kinds.map(x=>`<button class="chip ${state.morph.kind===x?'active':''}" data-mf="kind:${x}">${x}</button>`).join('')}</div></div>`}
function morphCard(e){return `<div class="morphcard"><div class="morph">${esc(e.m)}</div><div class="meta">${esc(e.type)} · ${esc(e.origin)}</div><div class="meaning">${esc(e.meaning)}</div><div class="muted">${esc(e.examples)}</div><div class="row" style="margin-top:6px">${(e.cats||[]).map(tag).join('')}</div></div>`}
function morph(){const item=letters[state.cur],base=entriesFor(item.l),list=filterMorph(base);return `<div class="content"><div class="soft"><div class="title">${item.l} Word Parts</div><div class="muted">${base.length} entries · ${typeCount(base,'prefix')} prefixes · ${typeCount(base,'root')} roots · ${typeCount(base,'suffix')} suffixes</div></div>${filters()}<div class="muted">Showing ${list.length} of ${base.length} entries for ${item.l}.</div><div class="grid">${list.map(morphCard).join('')}</div></div>`}
function counts(){const all=allMorph(),list=filterMorph(all),tot={total:all.length,prefix:typeCount(all,'prefix'),root:typeCount(all,'root'),suffix:typeCount(all,'suffix')};return `<div class="content"><div class="card"><div class="title">Morpheme Index</div><div class="muted">Full prefix, root, suffix, origin, and category browser.</div><div class="countgrid">${Object.entries(tot).map(([k,v])=>`<div class="countcard"><div class="big">${v}</div><div class="small">${k}</div></div>`).join('')}</div></div>${filters()}<div class="muted">Showing ${list.length} matching entries.</div><div class="grid">${list.map(morphCard).join('')}</div></div>`}
function stem(){const cats=['All',...new Set(STEM_TOPICS.map(x=>x.cat||x.area||'STEM'))];const list=state.stemCat==='All'?STEM_TOPICS:STEM_TOPICS.filter(x=>(x.cat||x.area)===state.stemCat);return `<div class="content"><div class="card"><div class="title">Formula Lab</div><div class="muted">STEM formula cards, method guides, examples, and diagrams.</div><div class="row" style="margin-top:8px">${cats.map(c=>`<button class="chip ${state.stemCat===c?'active':''}" data-stemcat="${esc(c)}">${esc(c)}</button>`).join('')}</div></div><div class="stemgrid">${[...QUICK_STEM_METHODS,...list].map(s=>`<div class="soft"><div class="name">${esc(s.title||s.subject||s.name)}</div><div class="muted">${esc(s.sub||s.area||s.cat||'')}</div>${s.svg?`<div class="svgbox">${s.svg}</div>`:''}${s.caption?`<div class="text">${esc(s.caption)}</div>`:''}${s.reality?`<div class="muted">${esc(s.reality)}</div>`:''}${s.formula?`<div class="formula">${esc(s.formula)}</div>`:''}${s.steps?section('Method')+s.steps.map((x,i)=>`<div class="text">${i+1}. ${esc(x)}</div>`).join(''):''}${s.example?section('Example')+`<div class="text">${esc(s.example)}</div>`:''}</div>`).join('')}</div></div>`}
const STRAT_CATS=['All','Reading','Writing','Pronunciation','Foreign Language Listening','Memory'];
function strategy(){const list=state.strategy==='All'?STRATEGY_CARDS:STRATEGY_CARDS.filter(s=>s.cat===state.strategy);return `<div class="content"><div class="card"><div class="title">Study Science</div><div class="muted">Research-backed strategies for reading, writing, pronunciation, listening, and memory.</div><div class="row" style="margin-top:8px">${STRAT_CATS.map(c=>`<button class="chip ${state.strategy===c?'active':''}" data-strat="${esc(c)}">${esc(c)}</button>`).join('')}</div></div>${list.map(s=>`<div class="soft"><div class="name">${esc(s.title)}</div><div class="muted">${esc(s.sub||s.cat)}</div>${s.formula?`<div class="formula">${esc(s.formula)}</div>`:''}${section('Method')}${(s.steps||[]).map((x,i)=>`<div class="text">${i+1}. ${esc(x)}</div>`).join('')}${s.topics?section('Topics')+s.topics.map(t=>`<div class="text"><span class="smalltitle">${esc(t.t||t.title)}</span> — ${esc(t.d||t.desc)}</div>`).join(''):''}</div>`).join('')}</div>`}
const TRACKS=[['quiz','Mixed Quiz'],['ap','AP'],['clep','CLEP'],['accuplacer','ACCUPLACER']], QUIZ_CATS=[['mixed','Mixed'],['arithmetic','Arithmetic'],['algebra','Algebra'],['geometry','Geometry'],['statistics','Statistics'],['calculus','Calculus'],['chemistry','Chemistry'],['reading','Reading'],['writing','Writing'],['morphemes','Morphemes']], AP_CATS=[['calc-ab','Calculus AB'],['calc-bc','Calculus BC'],['chemistry','Chemistry'],['physics-1','Physics 1'],['statistics','Statistics']], CLEP_CATS=[['college-algebra','College Algebra'],['precalculus','Precalculus'],['chemistry','Chemistry']], ACCU_CATS=[['arithmetic','Arithmetic'],['quantitative-reasoning','Quantitative Reasoning'],['advanced-algebra','Advanced Algebra'],['reading','Reading'],['writing','Writing'],['essay','WritePlacer Essay']];
function pool(){let q=state.quiz;if(q.track==='quiz'){if(q.cat==='mixed')return Object.values(QB).flat();return QB[q.cat]||[]} if(q.track==='ap')return QB[q.ap]||QB.chemistry||[]; if(q.track==='clep')return QB[q.clep]||QB.algebra||[]; return QB[q.accu]||[]}
function pickQuestion(){const p=pool(); if(!p.length){state.quiz.current=null;return} let unseen=p.filter(x=>!state.quiz.seen[x._id||x.prompt]); if(!unseen.length){state.quiz.seen={};unseen=p} state.quiz.current=unseen[Math.floor(Math.random()*unseen.length)]; state.quiz.chosen=null}
function quiz(){if(['ap','clep','accuplacer'].includes(state.mode))state.quiz.track=state.mode;if(!state.quiz.current)pickQuestion();const q=state.quiz,p=pool(),unseen=p.filter(x=>!q.seen[x._id||x.prompt]).length,pct=q.total?Math.round(q.score/q.total*100):0,guide=q.track==='quiz'?null:STUDY_GUIDES[q.track];const selectors=q.track==='quiz'?QUIZ_CATS:q.track==='ap'?AP_CATS:q.track==='clep'?CLEP_CATS:ACCU_CATS;const active=q.track==='quiz'?q.cat:q.track==='ap'?q.ap:q.track==='clep'?q.clep:q.accu;return `<div class="content"><div class="card herocard"><div class="heroiconwrap">${icons.quiz}</div><div class="herotitle">Unified Quiz / Exam Lab</div><div class="herosub">Full Practice setup from the HTML app: AP, CLEP, ACCUPLACER, adaptive scoring, explanations, topic tracking, and a live answer sheet.</div><div class="row" style="justify-content:center">${TRACKS.map(([id,l])=>`<button class="chip ${q.track===id?'active':''}" data-track="${id}">${l}</button>`).join('')}</div>${guide?`<a class="rescard" style="margin-top:12px" href="${guide.url}" target="_blank"><span class="resicon">${icons.link}</span><span><b>${esc(guide.title)}</b><br><span class="muted">${esc(guide.desc)}</span></span></a>`:''}</div><div class="dash"><div class="card">${section(q.track==='quiz'?'Category':q.track==='ap'?'AP Exam':q.track==='clep'?'CLEP Exam':'Section')}<div class="row">${selectors.map(([id,l])=>`<button class="chip ${active===id?'active':''}" data-qsel="${id}">${l}</button>`).join('')}</div></div><div class="card"><div class="name">Study Session</div><div class="statgrid"><div class="statbox"><div class="statvalue">${p.length}</div><div class="statlabel">Pool</div></div><div class="statbox"><div class="statvalue">${unseen}</div><div class="statlabel">Unseen</div></div><div class="statbox"><div class="statvalue">${q.score}/${q.total}</div><div class="statlabel">Score</div></div><div class="statbox"><div class="statvalue">${pct}%</div><div class="statlabel">Accuracy</div></div></div><div class="meter"><div class="meterfill" style="width:${pct}%"></div></div>${q.track==='accuplacer'?`<div class="band ${q.scaled>=271?'pass':'warn'}">${q.scaled>=271?'271+ target met':'Target: 271+'} · Scaled ${q.scaled} · Level ${q.difficulty}</div>`:''}</div></div>${q.track==='accuplacer'?accuResources():''}${q.track==='accuplacer'&&q.accu==='essay'?essayCard():questionCard()}${report()}</div>`}
function questionCard(){const q=state.quiz,c=q.current;if(!c)return `<div class="card"><div class="muted">No questions found for this section.</div></div>`;let answered=q.chosen!==null,ok=answered&&q.chosen===c.answer;return `<div class="card"><div class="questiontop"><div class="focus">${esc(c.focus)}</div><div class="level">Difficulty ${'●'.repeat(c.level||1)}${'○'.repeat(Math.max(0,5-(c.level||1)))}</div></div>${c.passage?`<div class="passage text">${esc(c.passage)}</div>`:''}<div class="promptbox"><div class="prompt">${esc(c.prompt)}</div></div><div class="options">${c.options.map((o,i)=>`<button class="option ${answered&&i===c.answer?'good':''} ${answered&&q.chosen===i&&i!==c.answer?'bad':''}" data-answer="${i}"><span class="bubble">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}</div>${answered?`<div class="feedback ${ok?'good':'bad'}"><div class="feedbacktitle">${ok?'Correct — nice work.':`Not quite. Correct answer: ${esc(c.options[c.answer])}`}</div><div class="text">${esc(c.why)}</div><div class="text">${esc(c.how)}</div></div>`:''}<div class="actionrow"><button class="btn" data-qreset>Reset session</button><button class="btn primary" data-qnext>Next question</button></div></div>`}
function accuResources(){return `<div class="card"><div class="name">ACCUPLACER Resources</div>${section('Official College Board Sample Questions')}<div class="resourcegrid">${ACCU_SAMPLE_PDFS.map(p=>`<a class="rescard" href="${p.url}" target="_blank"><span class="resicon">${icons.link}</span><span><b>${esc(p.label)}</b><br><span class="muted">${esc(p.desc)}</span></span></a>`).join('')}</div>${section('IXL Skill Plans — 271–300 Score Band Topics')}<div class="resourcegrid">${ACCU_IXL_PLANS.map(p=>`<div class="ixlcard"><a href="${p.url}" target="_blank"><b>${esc(p.label)}</b></a><div>${p.topics.map(t=>`<span class="topicpill">${esc(t)}</span>`).join('')}</div></div>`).join('')}</div></div>`}
function essayCard(){let words=state.quiz.essay.trim()?state.quiz.essay.trim().split(/\s+/).length:0;return `<div class="card">${section('WritePlacer Essay Practice')}<div class="prompt">Write a 300–600 word essay taking a clear position on a debatable issue. Use a thesis, organized body paragraphs, specific evidence, and a conclusion.</div><textarea class="essay" data-essay rows="10" placeholder="Type your essay here…">${esc(state.quiz.essay)}</textarea><div class="meta">Words: ${words} · Target: 300–600</div><div class="feedback good"><div class="feedbacktitle">Rubric reminder</div><div class="text">Score for focus, organization, development/support, sentence control, and conventions. Aim for a clear thesis, specific examples, transitions, and error-controlled paragraphs.</div></div></div>`}
function report(){const q=state.quiz;return `<div class="card"><div class="name">Answer Sheet</div>${q.track==='accuplacer'?`<div class="soft"><div class="muted">Weak topics: ${Object.keys(q.missed).length?Object.entries(q.missed).map(([k,v])=>`${k} (${v})`).join(' · '):'none yet'}</div><div class="muted">Strong topics: ${Object.keys(q.strong).length?Object.entries(q.strong).map(([k,v])=>`${k} (${v})`).join(' · '):'none yet'}</div></div>`:''}${!q.sheet.length?`<div class="muted">Answer questions to build a learn-as-you-go review sheet.</div>`:q.sheet.map((r,i)=>`<div class="sheetrow ${r.ok?'ok':'no'}"><span class="sheetnum">${q.sheet.length-i}</span><div><div class="smalltitle">${esc(r.focus)}</div><div class="text">${esc(r.prompt)}</div><div class="meta">Your answer: ${esc(r.chosen)} · Correct: ${esc(r.correct)}</div><div class="meta">Why: ${esc(r.why)}</div><div class="meta">How: ${esc(r.how)}</div></div></div>`).join('')}</div>`}
function bottom(){if(!letterMode())return '';const item=letters[state.cur];return `<div class="bottomnav"><button class="btn" data-prev>Prev</button><div class="pos">${item.l} — ${state.cur+1} of ${letters.length}</div><button class="btn primary" data-next>Next</button></div>`}
function tabs(){return `<div class="tabs">${[['explore','Roots',icons.roots],['vocab','Words',icons.words],['morph','Parts',icons.parts],['quiz','Practice',icons.quiz],['stem','Formula',icons.lab],['strategy','More',icons.more]].map(([m,l,ic])=>`<button class="tab ${activeMode(m)?'active':''}" data-mode="${m}">${ic}<span>${l}</span></button>`).join('')}</div>`}
function render(){const screen={explore,vocab,morph,counts,stem,strategy,quiz,ap:quiz,clep:quiz,accuplacer:quiz}[state.mode]||explore;$('#app').innerHTML=topbar()+screen()+bottom()+tabs();bind()}
function bind(){ $$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render()}); $('[data-reset-streak]')?.addEventListener('click',()=>{state.streak=0;localStorage.ls_streak=0;render()}); $('[data-timer]')?.addEventListener('click',()=>{if(state.running){state.elapsed+=Date.now()-state.start}else state.start=Date.now();state.running=!state.running;render()}); $('[data-prev]')?.addEventListener('click',()=>{state.cur=(state.cur-1+letters.length)%letters.length;render()}); $('[data-next]')?.addEventListener('click',()=>{state.cur=(state.cur+1)%letters.length;render()}); $$('[data-reveal]').forEach(b=>b.onclick=()=>{state.revealed[b.dataset.reveal]=!state.revealed[b.dataset.reveal];render()}); $('[data-mq]')?.addEventListener('input',e=>{state.morph.q=e.target.value;render()}); $$('[data-mf]').forEach(b=>b.onclick=()=>{let [k,v]=b.dataset.mf.split(':');state.morph[k]=v;render()}); $$('[data-stemcat]').forEach(b=>b.onclick=()=>{state.stemCat=b.dataset.stemcat;render()}); $$('[data-strat]').forEach(b=>b.onclick=()=>{state.strategy=b.dataset.strat;render()}); $$('[data-track]').forEach(b=>b.onclick=()=>{state.quiz.track=b.dataset.track;state.mode=b.dataset.track;state.quiz.current=null;render()}); $$('[data-qsel]').forEach(b=>b.onclick=()=>{let q=state.quiz;if(q.track==='quiz')q.cat=b.dataset.qsel;else if(q.track==='ap')q.ap=b.dataset.qsel;else if(q.track==='clep')q.clep=b.dataset.qsel;else q.accu=b.dataset.qsel;q.current=null;q.chosen=null;render()}); $$('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer)); $('[data-qnext]')?.addEventListener('click',()=>{pickQuestion();render()}); $('[data-qreset]')?.addEventListener('click',()=>{Object.assign(state.quiz,{score:0,total:0,chosen:null,seen:{},sheet:[],missed:{},strong:{},scaled:250,difficulty:1});pickQuestion();render()}); $('[data-essay]')?.addEventListener('input',e=>{state.quiz.essay=e.target.value;render()}) }
function answer(i){let q=state.quiz,c=q.current;if(!c||q.chosen!==null)return;q.chosen=i;q.total++;if(i===c.answer){q.score++;state.streak++;localStorage.ls_streak=state.streak}else state.streak=0;localStorage.ls_streak=state.streak;q.seen[c._id||c.prompt]=true;let ok=i===c.answer;if(q.track==='accuplacer'){if(ok){q.scaled=Math.min(300,q.scaled+3);q.difficulty=Math.min(5,q.difficulty+1);q.strong[c.topic]=(q.strong[c.topic]||0)+1}else{q.scaled=Math.max(200,q.scaled-2);q.difficulty=Math.max(1,q.difficulty-1);q.missed[c.topic]=(q.missed[c.topic]||0)+1}}q.sheet.unshift({id:c._id||c.prompt,ok,focus:c.focus,prompt:c.prompt,chosen:c.options[i],correct:c.options[c.answer],why:c.why,how:c.how});q.sheet=q.sheet.slice(0,20);render()}
setInterval(()=>{if(state.running){let t=$('[data-timer]');if(t)t.textContent=timerLabel()}},500);render();
